/* Ad hiding + compact layout integration. Local fixtures, no Facebook account. */
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require('playwright');
const base=path.resolve(__dirname,'..');
const asset=name=>fs.readFileSync(path.join(base,'app/src/main/assets',name),'utf8');
const image='data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200"><rect width="200" height="200" fill="#617c65"/></svg>');
function card(id,title='Listing '+id){return `<div class="cell" id="card-${id}"><a href="/marketplace/item/${id}/" onclick="event.preventDefault();window.clicked='${id}'"><div class="photo"><img src="${image}"></div><div class="caption"><span>$${id}00</span><span>${title}</span></div><button onclick="event.stopPropagation();event.preventDefault();window.saved='${id}'">Save</button></a></div>`;}
function advert(id,label='<div>Ad</div>'){return `<div id="ad-shell-${id}" style="min-height:500px;padding:20px"><div id="ad-${id}"><a href="https://example.test/advert" onclick="event.preventDefault();window.adClicked=true"><div class="photo"><img src="${image}"></div></a><strong>Example advertiser</strong>${label}</div></div>`;}
function fixture(){return `<!doctype html><html><head><meta name="viewport" content="width=device-width, initial-scale=1"><style>
html{height:100%;overflow-x:hidden}body{height:100%;margin:0;background:#242526;color:white;font:16px Arial}a{color:inherit;text-decoration:none}.cell{width:580px}.photo{position:relative;padding-top:100%}.photo img{position:absolute;inset:0;width:100%;height:100%}.caption span{display:block}.row{display:flex;flex-wrap:wrap}button{padding:8px;background:#333;color:white;border:0}
#spacer{height:60px}#page{position:relative;top:56px}#location{padding:18px 0;min-height:60px;flex-basis:90px}.mixed{min-height:700px}
</style></head><body><div id="spacer" role="presentation"><div style="display:none">Old Facebook navigation</div></div><div id="page"><main role="main"><div id="location"><svg width="12" height="12" aria-hidden="true"><title>Location</title></svg><span role="link" onclick="window.locationClicked=true">Gold Coast · 250 km</span></div>
<div id="collection"><div class="row">${card(1)}${card(2,'Ad')}</div><div class="mixed" id="batch-1">${advert(1)}${card(3)}</div><div class="mixed" id="batch-2">${advert(2,'<div><span>Spon</span><span>sored</span></div>')}${card(4,'Sponsored')}</div><div class="row">${card(5)}${card(6)}</div></div>
<div role="status" id="notice">Advertising preferences are unchanged</div></main></div></body></html>`;}
(async()=>{
const browser=await chromium.launch({executablePath:process.env.TEST_CHROME||chromium.executablePath(),args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:384,height:700},hasTouch:true,isMobile:true});page.setDefaultTimeout(1500);
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',r=>r.fulfill({status:200,contentType:'text/html; charset=utf-8',body:fixture()}));
async function open(url='/marketplace/',compact=true){await page.goto('https://www.facebook.com'+url);await page.evaluate(asset('adblock.js'));if(compact){await page.evaluate(c=>{window.__marketOnlyCss=c},asset('marketplace.css'));await page.evaluate(asset('marketplace.js'));}await page.waitForTimeout(350);}
await open();const results=[];async function test(name,fn){try{await fn();results.push({name,passed:true});console.log('PASS:',name)}catch(e){results.push({name,passed:false,error:e.message});console.error('FAIL:',name,e.message)}}
await test('plain div Ad disclosure hides its full ad and reserved wrapper',async()=>{assert.equal(await page.locator('#ad-shell-1').isVisible(),false);assert.equal(await page.locator('#ad-shell-1').evaluate(e=>e.getBoundingClientRect().height),0);});
await test('split Sponsored disclosure is recognised',async()=>assert.equal(await page.locator('#ad-shell-2').isVisible(),false));
await test('ordinary listings named Ad or Sponsored remain visible',async()=>{assert(await page.locator('#card-2').isVisible());assert(await page.locator('#card-4').isVisible());assert.equal(await page.locator('a[href*="/marketplace/item/"]').count(),6);});
await test('the next listing stays visible without the ad row height',async()=>{assert(await page.locator('#card-3').isVisible());assert((await page.locator('#batch-1').boundingBox()).height<300);await page.locator('#card-3 [data-mo-summary]').click();assert.equal(await page.evaluate(()=>window.clicked),'3');});
await test('consecutive ad rows reuse the empty column for real listings',async()=>{const a=await page.locator('#card-3').boundingBox(),b=await page.locator('#card-4').boundingBox();assert.equal(a.y,b.y);assert(Math.abs(a.width-190)<1&&Math.abs(b.width-190)<1);assert(b.x>a.x);});
await test('original save button remains functional',async()=>{await page.locator('#card-3 button').click();assert.equal(await page.evaluate(()=>window.saved),'3');});
await test('presentation spacer, hidden text and relative offset do not leave a top band',async()=>{await page.evaluate(()=>scrollTo(0,0));const first=await page.locator('#card-1 [data-mo-photo]').boundingBox();assert(first.y<=44,JSON.stringify(first));assert(await page.locator('#location svg').isVisible());});
await test('ad hiding can be switched off and on without deleting content',async()=>{await page.evaluate(()=>{window.__marketOnlyHideAds=false;window.__marketOnlyAdSweep()});assert(await page.locator('#ad-shell-1').isVisible());assert.equal(await page.locator('[data-mo-ad-single]').count(),0);await page.locator('#ad-1 strong').click();await page.evaluate(()=>{window.__marketOnlyHideAds=true;window.__marketOnlyAdSweep()});assert.equal(await page.locator('#ad-shell-1').isVisible(),false);assert.equal(await page.locator('#ad-shell-1').count(),1);});
await test('ads arriving later are hidden automatically',async()=>{await page.locator('#collection').evaluate((e,html)=>e.insertAdjacentHTML('beforeend',html),advert(3,'<span aria-label="Sponsored"><span>Sponsored</span></span>'));await page.waitForTimeout(400);assert.equal(await page.locator('#ad-shell-3').isVisible(),false);});
await test('a recycled ad wrapper becomes visible when it contains a real listing',async()=>{await page.locator('#ad-shell-3').evaluate((e,html)=>e.innerHTML=html,card(7));await page.waitForTimeout(400);assert(await page.locator('#card-7').isVisible());assert.equal(await page.locator('#ad-shell-3').getAttribute('data-mo-ad-hidden'),null);});
await test('repeated scrolls can load subsequent batches after hidden ads',async()=>{
 await page.evaluate(()=>{window.pages=0;addEventListener('scroll',()=>{const d=document.scrollingElement;if(d.scrollTop+d.clientHeight>=d.scrollHeight-180&&window.pages<3){window.pages++;const e=document.createElement('div');e.className='next-page';e.style.height='700px';e.textContent='More results';document.querySelector('main').appendChild(e)}})});
 await page.mouse.move(180,450);for(let n=0;n<18;n++){await page.mouse.wheel(0,700);await page.waitForTimeout(120);if(await page.evaluate(()=>window.pages===3))break}assert.equal(await page.evaluate(()=>window.pages),3);
});
await test('ad-only mode works when the compact layout is disabled',async()=>{await open('/marketplace/',false);assert.equal(await page.locator('#ad-shell-1').isVisible(),false);assert(await page.locator('#card-2').isVisible());assert.equal(await page.locator('html').getAttribute('data-mo-page'),null);});
await test('unlabelled detail content and login forms are not hidden',async()=>{await open('/marketplace/item/1/',false);assert(await page.locator('#ad-shell-1').isVisible());await open('/login/',false);assert(await page.locator('#ad-shell-1').isVisible());});
await test('non-ad notices remain visible and scripts report no errors',async()=>{await open();assert(await page.locator('#notice').isVisible());assert.deepEqual(errors,[]);});
await test('an advert with a scripted link is hidden without an href',async()=>{await page.locator('#collection').evaluate((e,html)=>{const wrapper=document.createElement('div');wrapper.innerHTML=html;const a=wrapper.querySelector('a');const link=document.createElement('div');link.setAttribute('role','link');link.innerHTML=a.innerHTML;a.replaceWith(link);e.appendChild(wrapper)},advert(8));await page.waitForTimeout(350);assert.equal(await page.locator('#ad-shell-8').isVisible(),false);});
await test('margin correction stays applied after repeated layout passes',async()=>{await page.evaluate(()=>{for(let n=0;n<4;n++)window.__marketOnlyLayout()});await page.waitForTimeout(300);assert((await page.locator('#card-1 [data-mo-photo]').boundingBox()).y<=44);});
await test('a genuinely changed source offset is re-evaluated',async()=>{await page.locator('#page').evaluate(e=>e.style.top='-10px');await page.waitForTimeout(350);assert.equal(await page.locator('#page').getAttribute('data-mo-top-offset'),null);await page.locator('#page').evaluate(e=>e.style.top='56px');await page.waitForTimeout(350);assert.equal(await page.locator('#page').evaluate(e=>getComputedStyle(e).top),'0px');});
await test('layout report contains geometry without account or listing content',async()=>{const report=await page.evaluate(()=>window.__marketOnlyLayoutReport());const parsed=JSON.parse(report);assert(parsed.location.length>0&&parsed.firstListing.length>0);for(const text of ['Gold Coast','Example advertiser','facebook.com','marketplace/item','example.test','Listing 1'])assert(!report.includes(text));assert(report.length<30000);});
await page.screenshot({path:path.join(base,'test-output/adblock-fixture.png'),fullPage:true});
fs.writeFileSync(path.join(base,'test-output/adblock-results.json'),JSON.stringify({scope:'Controlled browser fixtures, not live Facebook or Android.',results},null,2));
await browser.close();if(results.some(r=>!r.passed))process.exitCode=1;
})();
