/* Regression driven by the phone report: 360px viewport, 178px normal cards,
   87px affected cards. Facebook's actual DOM was not supplied. */
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require('playwright');
const base=path.resolve(__dirname,'..'),asset=n=>fs.readFileSync(path.join(base,'app/src/main/assets',n),'utf8');
const image='data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200"><rect width="200" height="200" fill="#447182"/></svg>');
function wrappedCard(id,depth){let content=`<a href="/marketplace/item/${id}/" id="card-${id}" onclick="event.preventDefault();window.opened=${id}"><div class="photo"><div><div><div><div><img src="${image}"></div></div></div></div></div><div class="caption"><span>$7,000</span><span>Listing ${id}</span><span>Gold Coast, QLD</span></div></a><button onclick="window.saved=${id}">Save</button>`;for(let n=0;n<depth;n++)content='<div class="wrapper">'+content+'</div>';return `<div class="slot" id="slot-${id}">${content}</div>`;}
function ad(){return `<div id="advert"><a href="https://example.test/advert"><img src="${image}"></a><span>Ad</span></div>`;}
const html=`<html><head><meta name="viewport" content="width=device-width, initial-scale=1"><style>html{overflow-y:scroll}body{margin:0;color:white;background:#242526;font:16px Arial}.row{display:flex;gap:4px;flex-wrap:wrap}.slot{width:calc((100% - 4px)/2)}.photo{position:relative;padding-top:100%}.photo img{position:absolute;inset:0;width:100%;height:100%}.caption span{display:block}a{color:inherit;text-decoration:none}</style></head><body><main role="main"><div id="results"><div class="row">${wrappedCard(1,6)}${wrappedCard(2,6)}</div>${ad()}<div class="row" id="deep-single">${wrappedCard(3,20)}</div><div class="row" id="deep-pair">${wrappedCard(4,24)}${wrappedCard(5,24)}</div><div class="row">${wrappedCard(6,4)}${wrappedCard(7,4)}</div></div></main></body></html>`;
(async()=>{
const browser=await chromium.launch({executablePath:process.env.TEST_CHROME||chromium.executablePath(),args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:360,height:628}});page.setDefaultTimeout(1500);const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',r=>r.fulfill({status:200,contentType:'text/html',body:html}));await page.goto('https://www.facebook.com/marketplace/');
await page.evaluate(asset('adblock.js'));await page.evaluate(c=>window.__marketOnlyCss=c,asset('marketplace.css'));await page.evaluate(asset('marketplace.js'));await page.waitForTimeout(350);
const results=[];async function test(name,fn){try{await fn();results.push({name,passed:true});console.log('PASS:',name)}catch(e){results.push({name,passed:false,error:e.message});console.error('FAIL:',name,e.message)}}
const width=async id=>(await page.locator('#card-'+id).boundingBox()).width;
await test('deep singleton retains the normal 178px card width after an ad is hidden',async()=>{assert.equal(await width(1),178);assert.equal(await width(3),178,'deep card width: '+await width(3));assert.equal(await page.locator('#advert').isVisible(),false);});
await test('deeply nested paired listings each occupy one full column',async()=>{assert.equal(await width(4),178);assert.equal(await width(5),178);const a=await page.locator('#card-4').boundingBox(),b=await page.locator('#card-5').boundingBox();assert.equal(a.y,b.y);assert.equal(b.x,182)});
await test('deep card captions and photos match the normal card width',async()=>{assert.equal((await page.locator('#card-3 img').boundingBox()).width,178);assert.equal((await page.locator('#card-3 [data-mo-summary]').boundingBox()).width,178);assert.equal(await page.locator('#card-3 [data-mo-summary-title]').textContent(),'$7,000 · Listing 3')});
await test('deep listing link and its original Save control still work',async()=>{await page.locator('#card-3 [data-mo-summary]').click();assert.equal(await page.evaluate(()=>window.opened),3);await page.locator('#slot-3 button').click();assert.equal(await page.evaluate(()=>window.saved),3)});
await test('additional wrappers arriving later cannot halve the card again',async()=>{await page.locator('#card-3').evaluate(e=>{let wrapper=e;for(let n=0;n<18;n++){const p=document.createElement('div');wrapper.replaceWith(p);p.appendChild(wrapper);wrapper=p}});await page.waitForTimeout(400);assert.equal(await width(3),178)});
await test('deep rows remain correctly sized when adverts are restored',async()=>{await page.evaluate(()=>{window.__marketOnlyHideAds=false;window.__marketOnlyAdSweep()});assert(await page.locator('#advert').isVisible());assert.equal(await width(3),178);await page.evaluate(()=>{window.__marketOnlyHideAds=true;window.__marketOnlyAdSweep()})});
await test('resizing and repeated passes preserve one half-screen column',async()=>{for(const w of [320,412,360]){await page.setViewportSize({width:w,height:628});await page.evaluate(()=>{for(let n=0;n<4;n++)window.__marketOnlyLayout()});assert(Math.abs(await width(3)-(w-4)/2)<1);assert(Math.abs(await width(4)-(w-4)/2)<1);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))}});
await test('layout settles without repeated DOM mutations',async()=>{await page.waitForTimeout(400);const n=await page.evaluate(()=>new Promise(resolve=>{let count=0;const o=new MutationObserver(r=>count+=r.length);o.observe(document.body,{childList:true,attributes:true,subtree:true});setTimeout(()=>{o.disconnect();resolve(count)},400)}));assert.equal(n,0);assert.deepEqual(errors,[])});
await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(base,'test-output/deep-container-fixture.png'),fullPage:true});
fs.writeFileSync(path.join(base,'test-output/deep-container-results.json'),JSON.stringify({scope:'Controlled deep DOM fixtures based on reported widths; not actual Facebook DOM.',results},null,2));
await browser.close();if(results.some(r=>!r.passed))process.exitCode=1;
})();
