/* Regression: actual description text must follow its heading across listing templates. */
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright');
const base=path.resolve(__dirname,'..'),asset=n=>fs.readFileSync(path.join(base,'app/src/main/assets',n),'utf8');
const heading='<div id="description-heading"><h2>Seller\'s description</h2></div>';
const body='<div id="description-body"><div dir="auto"><span id="preview">Range Rover Sport 2007 L320. Daily driver. </span><span id="expanded" hidden>Currently registered. Air suspension works. Moving overseas.</span><button id="expand" onclick="const s=document.querySelector(\'#expanded\');s.hidden=!s.hidden;this.textContent=s.hidden?\'See more\':\'See less\'">See more</button></div></div>';
const status='<div role="status" aria-live="polite" id="status"></div>';
function fixture(type){
 const title='<section id="title"><h1>Example listing</h1><p id="listed">Listed 3 hours ago</p></section>';
 const message='<section id="message"><span>Send seller a message</span><form onsubmit="event.preventDefault();window.sent=document.querySelector(\'#draft\').value"><input id="draft" aria-label="Message seller" value="Hey mate,"><button>Send</button></form></section>';
 const actions='<section id="actions"><button onclick="window.saved=true">Save</button><button onclick="window.shared=true">Share</button><button aria-label="More options" onclick="window.more=true">…</button></section>';
 const vehicle='<section id="vehicle"><h2>About this vehicle</h2><p>Driven 222,666 km</p><p>Automatic transmission</p></section>';
 const details='<h2 id="details-heading">Details</h2><div id="condition"><span>Condition</span><span>Used - Good</span></div>';
 const rest='<div id="map" role="img" aria-label="Map"></div><p id="location">Gold Coast · Location is approximate</p><section id="seller"><h2>Seller information</h2><p>Seller name</p></section>';
 let middle=title+message+actions+vehicle+heading+status+body+rest;
 if(type==='outside')middle='<div id="headings">'+title+message+actions+vehicle+heading+'</div><div id="body-shell">'+body+rest+'</div>';
 if(type==='rich')middle=title+message+actions+vehicle+heading+status+body.replace('Range Rover Sport 2007 L320. Daily driver. ','<h3>Condition report</h3>Range Rover Sport 2007 L320. <a href="/marketplace/item/other/" onclick="event.preventDefault();window.link=true">Related parts</a>')+rest;
 if(type==='generic'||type==='short')middle=title+message+actions+'<section id="details">'+details+(type==='short'?'<p id="description-body">Pergola available for collection this weekend.</p>':body)+'</section>'+rest;
 if(type==='loading')middle=title+message+actions+vehicle+heading+status+'<div id="pending-body"></div>'+rest;
 return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;background:#242526;color:#e4e6eb;font:16px Arial}section,#description-heading,#description-body,#details-heading,#condition,#location{padding:12px}h1{font-size:24px}h2{font-size:19px}button{padding:10px;color:white;background:#3a3b3c;border:0}#map{height:60px;background:#355}p{margin:8px 0}#condition{display:flex;gap:20px}#description-body{line-height:1.5}#description-heading h2{margin:0}main{padding-bottom:600px}</style></head><body><main role="main"><div id="sections">${middle}</div></main></body></html>`;
}
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.TEST_CHROME||chromium.executablePath(),args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:360,height:628},hasTouch:true,isMobile:true});page.setDefaultTimeout(1500);let type='split';const results=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',r=>r.fulfill({status:200,contentType:'text/html; charset=utf-8',body:fixture(type)}));
 async function open(t='split'){type=t;await page.goto('https://www.facebook.com/marketplace/item/1/');await page.evaluate(()=>window.original=Object.fromEntries(['description-body','expand','draft'].map(id=>{const e=document.getElementById(id);return [id,e&&{e,p:e.parentNode}]})));await page.evaluate(asset('adblock.js'));await page.evaluate(c=>window.__marketOnlyCss=c,asset('marketplace.css'));await page.evaluate(asset('marketplace.js'));await page.evaluate(asset('detail.js'));await page.waitForTimeout(400)}
 async function position(id){return page.locator(id).evaluate(e=>{const r=e.getBoundingClientRect();return {top:r.top,bottom:r.bottom}})}
 async function completeOrder(generic=false){
   const ids=['#listed','#actions',generic?'[data-mo-detail-generated-description]':'#description-heading','#description-body',generic?'#details-heading':'#vehicle','#message','#map','#seller'];let previous=-Infinity;
   for(const id of ids){const r=await position(id);assert(r.top>=previous-1,id+' is separated or out of order: '+r.top+' < '+previous);previous=r.bottom}
 }
 async function test(name,fn){try{await fn();results.push({name,passed:true});console.log('PASS:',name)}catch(e){results.push({name,passed:false,error:e.message});console.error('FAIL:',name,e.message)}}
 await test('description heading and text stay together across a status wrapper',async()=>{await open();await completeOrder()});
 await test('description outside the headings common parent joins the correct section',async()=>{await open('outside');await completeOrder()});
 await test('rich description headings and listing links remain part of the description',async()=>{await open('rich');await completeOrder();await page.locator('#description-body a').click();assert(await page.evaluate(()=>window.link))});
 await test('See more and See less keep the entire expanded description before the vehicle facts',async()=>{await open();for(let i=0;i<3;i++){await page.locator('#expand').click();await page.waitForTimeout(300);await completeOrder()}assert(await page.locator('#expanded').isVisible());assert.equal(await page.locator('#expand').innerText(),'See less')});
 await test('ordinary items get actions, complete description, condition details, then message',async()=>{await open('generic');await completeOrder(true);assert(await page.locator('#condition').isVisible());assert.equal(await page.locator('[data-mo-detail-generated-description]').count(),1)});
 await test('short ordinary descriptions without a See more button are also grouped',async()=>{await open('short');await completeOrder(true)});
 await test('moving a description preserves its original text, nodes, handlers and message draft',async()=>{await open('outside');await page.locator('#draft').fill('A draft stays here');await page.locator('#expand').click();await page.evaluate(()=>window.__marketOnlyDetailLayout());await completeOrder();assert(await page.evaluate(()=>Object.values(original).filter(Boolean).every(x=>x.e.isConnected&&x.e.parentNode===x.p)));assert.equal(await page.locator('#draft').inputValue(),'A draft stays here');assert.equal(await page.evaluate(()=>!!window.sent),false)});
 await test('the heading is not moved on its own while description content is loading',async()=>{await open('loading');assert.equal(await page.locator('[data-mo-detail-stack]').count(),0);await page.locator('#pending-body').evaluate((e,html)=>e.innerHTML=html,body);await page.waitForTimeout(450);await completeOrder()});
 await test('replacing collapsed description nodes keeps new content above the facts',async()=>{await open();await page.locator('#description-body').evaluate(e=>e.outerHTML='<div id="description-body"><p>Newly loaded full description with all original text.</p><button id="expand">See less</button></div>');await page.waitForTimeout(400);await completeOrder();assert((await page.locator('#description-body').innerText()).includes('Newly loaded full description'))});
 await test('switching from an ordinary listing to a vehicle removes only the generated heading',async()=>{await open('generic');await page.locator('#sections').evaluate((e,html)=>{e.innerHTML=new DOMParser().parseFromString(html,'text/html').querySelector('#sections').innerHTML;history.pushState({},'', '/marketplace/item/2/')},fixture('outside'));await page.waitForTimeout(450);await completeOrder();assert.equal(await page.locator('[data-mo-detail-generated-description]').count(),0)});
 await test('repeated passes do not duplicate headings or content',async()=>{await open('generic');await page.evaluate(()=>{for(let i=0;i<5;i++)window.__marketOnlyDetailLayout()});await page.waitForTimeout(400);await completeOrder(true);assert.equal(await page.locator('[data-mo-detail-generated-description]').count(),1);assert.equal(await page.locator('#description-body').count(),1);assert.deepEqual(errors,[])});
 fs.writeFileSync(path.join(base,'test-output/description-results.json'),JSON.stringify({scope:'Structural reproductions of separate headings/body and generic item templates; no live account or Android test.',results},null,2));await page.screenshot({path:path.join(base,'test-output/description-fixture.png'),fullPage:true});await browser.close();if(results.some(x=>!x.passed))process.exitCode=1;
})();
