/* Screenshot-shaped listing fixtures. No account, network service or Android device. */
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright');
const base=path.resolve(__dirname,'..'),asset=n=>fs.readFileSync(path.join(base,'app/src/main/assets',n),'utf8');
const img='https://scontent.example.fbcdn.net/photo-1.jpg',img2='https://scontent.example.fbcdn.net/photo-2.jpg';
const svg='<svg xmlns="http://www.w3.org/2000/svg" width="600" height="400"><rect width="600" height="400" fill="#5c7a68"/></svg>';
const ads=`<div id="ads-space" style="min-height:240px;padding:16px"><div><h2>Ads</h2><div class="ad-row"><a href="https://example.test/ad" onclick="event.preventDefault();window.adClicked=true"><img src="${img}">Example advertiser</a><div role="link"><img src="${img2}">Another advertiser</div></div></div></div>`;
const content={
 title:'<div id="title"><h1>1994 BMW Series 5</h1><b>A$1,800</b><p id="listed">Listed 3 hours ago in Gold Coast, QLD</p></div>',
 message:'<div id="message" class="section"><div><span>Send seller a message</span></div><form onsubmit="event.preventDefault();window.sent=document.querySelector(\'#draft\').value"><input id="draft" aria-label="Message seller" value="Hello, is this still available?"><button type="submit">Send</button></form></div>',
 actions:'<div id="actions" class="section"><button id="save" onclick="window.saved=true">Save</button><button id="share" onclick="window.shared=true">Share</button><button id="more" aria-label="More options" onclick="window.more=true">…</button></div>',
 vehicle:'<div id="vehicle" class="section"><h2><span>About this vehicle</span></h2><div class="specs"><span>Driven 300,000 km</span><span>Automatic transmission</span><span>Fuel type: Petrol</span></div><button id="vehicle-more" onclick="document.querySelector(\'#extra-spec\').hidden=false">See more</button><p id="extra-spec" hidden>Exterior: white</p></div>',
 description:'<div id="description" class="section"><h2><span>Seller\'s description</span></h2><div id="description-text">White BMW for sale. Body and paint are good.<button id="description-more" onclick="document.querySelector(\'#description-text\').append(\' Full original description.\');this.remove()">See more</button></div></div>',
 location:'<div id="location" class="section"><div class="map" role="img" aria-label="Map"></div><p>Gold Coast, QLD · Location is approximate</p></div>',
 seller:'<div id="seller" class="section"><h2>Seller information</h2><button id="seller-info" onclick="window.seller=true">Seller details</button><p>Joined Facebook in 2008</p></div>'
};
function fixture(kind='flat'){
 const sections=kind==='nested'?`<div id="title-group">${content.title}</div><div id="reused-wrapper"><div id="contact-wrapper">${content.message}${content.actions}</div><div id="detail-wrapper">${content.vehicle}${ads}<div id="description-wrapper">${content.description}${content.location}${content.seller}</div></div></div>`:Object.values({...content,location:undefined,seller:undefined}).filter(Boolean).slice(0,4).join('')+ads+content.description+content.location+content.seller;
 return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>html,body{margin:0;background:#242526;color:#e4e6eb;font:16px Arial}#frame{${kind==='dialog'?'position:fixed;top:56px;bottom:0;left:0;right:0;overflow:auto;':'padding-top:56px;'}}#spacer{height:56px}#gallery{background:#333}#hero{display:block;width:100%;height:220px;object-fit:contain}#thumbs{display:flex;justify-content:center;gap:8px;height:48px}#thumbs img{width:40px;height:40px}#title,.section{padding:16px;border-bottom:1px solid #424344}h1{font-size:25px;margin:0 0 8px}h2{font-size:19px;margin:0 0 14px}p{margin:10px 0}button{border:0;color:#65aeff;background:#3a3b3c;padding:10px;border-radius:6px}#actions{display:flex;gap:8px}#actions button{flex:1}form{display:flex;gap:8px;margin-top:8px}input{min-width:0;width:100%;padding:10px}.specs{display:grid;grid-template-columns:1fr 1fr;gap:12px}.ad-row{display:flex;gap:8px}.ad-row img{display:block;width:145px;height:145px}.map{height:60px;background:#355965}#description-text{line-height:1.5}#tail{height:240px}</style></head><body><div role="banner" style="position:fixed;height:56px">Facebook navigation</div><div id="frame" ${kind==='dialog'?'role="dialog" aria-modal="true"':''}><main role="main"><div id="spacer"></div><div id="gallery"><img id="hero" alt="Vehicle photo" src="${img}"><div id="thumbs"><button onclick="document.querySelector('#hero').src='${img}'"><img src="${img}"></button><button id="thumb2" onclick="document.querySelector('#hero').src='${img2}'"><img src="${img2}"></button></div></div><div id="sections">${sections}</div><div id="tail"></div></main></div></body></html>`;
}
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.TEST_CHROME||chromium.executablePath(),args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:360,height:628},isMobile:true,hasTouch:true});page.setDefaultTimeout(1800);const errors=[],results=[];page.on('pageerror',e=>errors.push(e.message));let kind='flat';
 await page.route('**/*',r=>r.fulfill({status:200,contentType:r.request().resourceType()==='image'?'image/svg+xml':'text/html',body:r.request().resourceType()==='image'?svg:fixture(kind)}));
 async function open(type='flat',url='/marketplace/item/1/',layout=true){kind=type;await page.goto('https://www.facebook.com'+url);await page.evaluate(()=>{window.originals=Object.fromEntries(['message','actions','vehicle','description','draft'].map(id=>{const e=document.getElementById(id);return [id,{element:e,parent:e.parentNode}]}))});await page.evaluate(asset('focus.js'));await page.evaluate(asset('adblock.js'));await page.evaluate(asset('media.js'));if(layout){await page.evaluate(c=>window.__marketOnlyCss=c,asset('marketplace.css'));await page.evaluate(asset('marketplace.js'));await page.evaluate(asset('detail.js'))}await page.evaluate(()=>{window.opened=[];window.__marketOnlyOpenPhoto=url=>opened.push(url)});await page.waitForTimeout(450)}
 const y=id=>page.locator('#'+id).evaluate(e=>e.getBoundingClientRect().top);
 async function order(){let last=-Infinity;for(const id of ['listed','actions','description','vehicle','message','location','seller']){const current=await y(id);assert(current>last,id+' appears in wrong order: '+current+' <= '+last);last=current}}
 async function test(name,fn){try{await fn();results.push({name,passed:true});console.log('PASS:',name)}catch(e){results.push({name,passed:false,error:e.message});console.error('FAIL:',name,e.message)}}
 await test('flat listing: listed time, actions, description, vehicle, message, location, seller',async()=>{await open();await order();assert.equal(await page.locator('#ads-space').isVisible(),false);assert.equal(await y('hero'),0)});
 await test('nested wrappers produce the same section order without moving real DOM nodes',async()=>{await open('nested');await order();assert(await page.evaluate(()=>Object.values(originals).every(x=>x.element.isConnected&&x.element.parentNode===x.parent)));assert.equal(await page.locator('#draft').inputValue(),'Hello, is this still available?')});
 await test('fixed listing dialog removes the 56px top inset and empty photo spacer',async()=>{await open('dialog');assert.equal(await y('frame'),0);assert.equal(await y('hero'),0);assert.equal(await page.locator('#frame').evaluate(e=>e.getBoundingClientRect().height),628);await order()});
 await test('Save, Share and the three-dot menu retain their original handlers',async()=>{await open('nested');for(const id of ['save','share','more'])await page.locator('#'+id).click();assert(await page.evaluate(()=>saved&&shared&&more));assert.equal(await page.evaluate(()=>!!window.sent),false)});
 await test('both See more controls and the existing message draft stay usable',async()=>{await open('nested');await page.locator('#draft').fill('Hey mate, when can I inspect?');await page.locator('#description-more').click();await page.locator('#vehicle-more').click();assert((await page.locator('#description-text').innerText()).includes('Full original description'));assert(await page.locator('#extra-spec').isVisible());await page.waitForTimeout(400);await order();assert.equal(await page.locator('#draft').inputValue(),'Hey mate, when can I inspect?');await page.locator('#message button[type=submit]').click();assert.equal(await page.evaluate(()=>window.sent),'Hey mate, when can I inspect?')});
 await test('gallery thumbnails and tap-to-enlarge survive reordering',async()=>{await open('nested');await page.locator('#thumb2').click();await page.locator('#hero').tap({position:{x:180,y:100}});assert.deepEqual(await page.evaluate(()=>opened),[img2])});
 await test('detail ads hide without compact layout and can be restored from the existing toggle',async()=>{await open('flat','/marketplace/item/1/',false);assert.equal(await page.locator('#ads-space').isVisible(),false);await page.evaluate(()=>{window.__marketOnlyHideAds=false;window.__marketOnlyAdSweep()});assert(await page.locator('#ads-space').isVisible());assert.equal(await page.locator('#ads-space').count(),1);await page.evaluate(()=>{window.__marketOnlyHideAds=true;window.__marketOnlyAdSweep()});assert.equal(await page.locator('#ads-space').isVisible(),false)});
 await test('late-loaded Ads carousels are hidden and seller content remains visible',async()=>{await open('nested');await page.locator('#seller').evaluate((e,html)=>e.insertAdjacentHTML('beforebegin',html.replace('ads-space','late-ads')),ads);await page.waitForTimeout(450);assert.equal(await page.locator('#late-ads').isVisible(),false);assert(await page.locator('#description').isVisible());assert(await page.locator('#seller').isVisible())});
 await test('a recycled ad section containing seller description is restored',async()=>{await open();await page.locator('#ads-space').evaluate(e=>e.innerHTML='<h2>Seller\'s description</h2><p>Additional seller notes</p>');await page.waitForTimeout(450);assert(await page.locator('#ads-space').isVisible())});
 await test('description text mentioning Ads is not treated as an ad carousel',async()=>{await open();await page.locator('#description-text').evaluate((e,url)=>e.innerHTML='<p>Ads</p><a href="https://example.test/manual">Manual</a><img style="width:80px;height:80px" src="'+url+'">',img);await page.waitForTimeout(450);assert(await page.locator('#description-text').isVisible());assert(await page.locator('#description-text img').isVisible())});
 await test('a live React-style replacement of the details gets the same order and keeps its new draft',async()=>{await open('nested');await page.locator('#sections').evaluate((e,parts)=>{e.innerHTML=parts;e.querySelector('#draft').value='New listing draft'},content.title+content.message+content.actions+content.vehicle+content.description+content.location+content.seller);await page.waitForTimeout(500);await order();assert.equal(await page.locator('#draft').inputValue(),'New listing draft')});
 await test('non-car listings keep actions and description above messaging without inventing vehicle details',async()=>{await open();await page.locator('#vehicle').evaluate(e=>e.remove());await page.waitForTimeout(350);assert(await y('actions')<await y('description'));assert(await y('description')<await y('message'));assert.equal(await page.locator('#vehicle').count(),0)});
 await test('nested dialog scrolling reaches the seller controls with touch input',async()=>{await open('dialog');const session=await page.context().newCDPSession(page);for(let n=0;n<8;n++){await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:180,y:570}]});for(let y=530;y>140;y-=40)await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:180,y}]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(160);const r=await page.locator('#seller-info').boundingBox();if(r.y>0&&r.y+r.height<628)break}const r=await page.locator('#seller-info').boundingBox();assert(r.y>0&&r.y+r.height<628);await page.touchscreen.tap(r.x+r.width/2,r.y+r.height/2);assert(await page.evaluate(()=>window.seller));assert.equal(await page.evaluate(()=>scrollY),0);assert(await page.locator('#frame').evaluate(e=>e.scrollTop>0))});
 await test('unrelated dialogs keep their own position and controls',async()=>{await open('dialog');await page.evaluate(()=>{document.body.insertAdjacentHTML('beforeend','<div role="dialog" id="filter" style="position:fixed;top:90px;left:20px;padding:24px;background:#222">Location<input id="city" value="Gold Coast"></div>')});await page.waitForTimeout(350);assert.equal(await y('filter'),90);assert.equal(await page.locator('#city').inputValue(),'Gold Coast')});
 await test('leaving a listing or entering login restores original presentation',async()=>{await open();await page.evaluate(()=>{history.pushState({},'', '/login/');window.__marketOnlyDetailLayout();window.__marketOnlyAdSweep();window.__marketOnlyLayout()});assert.equal(await page.locator('[data-mo-detail-stack],[data-mo-detail-pass],[data-mo-detail-order]').count(),0);assert(await y('message')<await y('description'));assert(await page.locator('#ads-space').isVisible())});
 await test('repeated passes settle without changing layout or issuing messages',async()=>{await open('nested');await page.evaluate(()=>{for(let i=0;i<4;i++){window.__marketOnlyDetailLayout();window.__marketOnlyAdSweep()}});await page.waitForTimeout(500);await order();assert.equal(await page.evaluate(()=>!!window.sent),false);assert.deepEqual(errors,[]);const mutations=await page.evaluate(()=>new Promise(resolve=>{let n=0;const o=new MutationObserver(r=>n+=r.length);o.observe(document.body,{subtree:true,childList:true,attributes:true});setTimeout(()=>{o.disconnect();resolve(n)},350)}));assert.equal(mutations,0)});
 await page.screenshot({path:path.join(base,'test-output/detail-fixture.png'),fullPage:true});fs.writeFileSync(path.join(base,'test-output/detail-results.json'),JSON.stringify({scope:'Controlled screenshot-shaped Chromium fixtures. Not an Android device or authenticated Facebook test.',results},null,2));await browser.close();if(results.some(r=>!r.passed))process.exitCode=1;
})();
