/* Reproduce reserved Facebook header space across tabs without modifying forms. */
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright');
const base=path.resolve(__dirname,'..'),asset=n=>fs.readFileSync(path.join(base,'app/src/main/assets',n),'utf8');
const fixture=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;background:#242526;color:white;font:16px Arial}#shell{padding-top:56px}main{position:relative;top:56px;margin-top:48px;padding:16px}#gap{height:56px}h1{margin:0 0 16px}form .field{margin-top:32px}input{padding:12px}#long{height:1400px}#notice{padding:16px;background:#345}</style></head><body><header role="banner" style="height:56px">Facebook navigation</header><div id="shell"><main role="main"><div id="gap"></div><section id="content"><h1 id="title">Item for sale</h1><form onsubmit="event.preventDefault();window.submitted=true"><label class="field" style="display:block">Title<input id="title-input" value="Car"></label><label class="field" style="display:block">Price<input value="200"></label><input type="file" id="photos" accept="image/*"><div id="long"></div><button id="save">Save draft</button></form></section></main></div></body></html>`;
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.TEST_CHROME||chromium.executablePath(),args:['--no-sandbox']});const results=[];
 const page=await browser.newPage({viewport:{width:360,height:628},isMobile:true,hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',r=>r.fulfill({status:200,contentType:'text/html',body:fixture}));
 async function open(url){await page.goto('https://www.facebook.com'+url);await page.evaluate(c=>window.__marketOnlyCss=c,asset('marketplace.css'));await page.evaluate(asset('focus.js'));await page.evaluate(asset('marketplace.js'));await page.evaluate(asset('detail.js'));await page.waitForTimeout(350)}
 async function test(name,fn){try{await fn();results.push({name,passed:true});console.log('PASS:',name)}catch(e){results.push({name,passed:false,error:e.message});console.error('FAIL:',name,e.message)}}
 for(const [name,url] of [['Sell','/marketplace/create/item/'],['Saved','/marketplace/you/saved/'],['Profile','/marketplace/you/'],['Listing','/marketplace/item/1/'],['Collections','/saved/']])await test(name+' collapses only leading header space',async()=>{await open(url);assert((await page.locator('#title').boundingBox()).y<=20);assert.equal(await page.locator('form .field').first().evaluate(e=>getComputedStyle(e).marginTop),'32px');assert.equal(await page.locator('#title-input').inputValue(),'Car');assert(await page.locator('#photos').isVisible());assert.equal(await page.locator('#long').evaluate(e=>e.getBoundingClientRect().height),1400)});
 await test('switching tabs without a page reload redoes spacing without changing form values',async()=>{await open('/marketplace/');await page.evaluate(()=>{history.pushState({},'', '/marketplace/create/item/');document.querySelector('#shell').style.paddingTop='84px';document.querySelector('#title-input').value='Draft stays';window.__marketOnlyLayout()});assert((await page.locator('#title').boundingBox()).y<=20);assert.equal(await page.locator('#title-input').inputValue(),'Draft stays')});
 await test('visible notices and loading controls are preserved',async()=>{await open('/marketplace/create/item/');await page.evaluate(()=>{const notice=document.createElement('div');notice.id='notice';notice.textContent='Finish your draft';document.querySelector('#content').prepend(notice);const loading=document.createElement('div');loading.id='loading';loading.setAttribute('role','progressbar');loading.style.height='40px';document.querySelector('#gap').append(loading);window.__marketOnlyLayout()});assert(await page.locator('#notice').isVisible());assert.equal((await page.locator('#loading').boundingBox()).height,40)});
 await test('scrolling to the final form action remains possible',async()=>{await open('/marketplace/create/item/');await page.mouse.move(180,400);await page.mouse.wheel(0,1800);await page.waitForTimeout(200);const r=await page.locator('#save').boundingBox();assert(r.y>=0&&r.y+r.height<=628);await page.touchscreen.tap(r.x+r.width/2,r.y+r.height/2);assert(await page.evaluate(()=>window.submitted));assert(await page.evaluate(()=>scrollY>500))});
 await test('modal positioning is untouched',async()=>{await open('/marketplace/create/item/');await page.evaluate(()=>{document.body.insertAdjacentHTML('beforeend','<div role="dialog" id="dialog" style="position:fixed;top:60px;left:20px;padding-top:40px">Location filter</div>');window.__marketOnlyLayout()});assert.equal((await page.locator('#dialog').boundingBox()).y,60);assert.equal(await page.locator('#dialog').evaluate(e=>getComputedStyle(e).paddingTop),'40px')});
 await test('login restores original top spacing',async()=>{await open('/marketplace/create/item/');await page.evaluate(()=>{history.pushState({},'', '/login/');window.__marketOnlyLayout()});assert((await page.locator('#title').boundingBox()).y>150);assert.equal(await page.locator('[data-mo-content-padding],[data-mo-content-spacer]').count(),0)});
 await test('repeated layout sweeps keep the same compact position',async()=>{await open('/marketplace/create/item/');for(let n=0;n<5;n++)await page.evaluate(()=>window.__marketOnlyLayout());assert.equal((await page.locator('#title').boundingBox()).y,16);assert.deepEqual(errors,[])});
 await page.screenshot({path:path.join(base,'test-output/sell-spacing-fixture.png')});fs.writeFileSync(path.join(base,'test-output/header-tabs-results.json'),JSON.stringify({scope:'Controlled header offset and form fixtures. Actual Facebook markup and Android native search row need phone acceptance.',results},null,2));await browser.close();if(results.some(r=>!r.passed))process.exitCode=1;
})();
