/* Visible card metadata must survive compact captions, including reduced prices. */
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright');
const base=path.resolve(__dirname,'..'),asset=n=>fs.readFileSync(path.join(base,'app/src/main/assets',n),'utf8');
const photo='https://scontent.example.fbcdn.net/listing.jpg';
const card=(id,caption)=>`<div id="card-${id}" class="cell"><a href="/marketplace/item/${id}/" onclick="event.preventDefault();window.opened=${id}"><div class="photo"><img src="${photo}"></div><div class="caption">${caption}</div></a></div>`;
const html=`<html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;background:#242526;color:white;font:16px Arial}.row{display:flex;flex-wrap:wrap}.cell{width:600px}.photo{position:relative;padding-top:100%}.photo img{position:absolute;inset:0;width:100%;height:100%}.caption span{display:block}a{color:inherit;text-decoration:none}</style></head><body><main><div class="row">${card(1,'<span>$900</span><span>Outdoor lounge</span><span>Gold Coast, QLD</span>')}${card(2,'<span>$1,000 <s><span>$2,000</span></s></span><span>2019 Subaru Outback</span><span>Murphys Creek, QLD</span>')}${card(3,'<span>$250</span><span>Couch</span>')}${card(4,'<span>$400</span><span>Parts</span><span>Brisbane</span>')}</div></main></body></html>`;
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.TEST_CHROME||chromium.executablePath(),args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:360,height:628},hasTouch:true,isMobile:true});page.setDefaultTimeout(1800);const results=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',r=>r.fulfill({status:200,contentType:r.request().resourceType()==='image'?'image/svg+xml':'text/html',body:r.request().resourceType()==='image'?'<svg xmlns="http://www.w3.org/2000/svg" width="400" height="400"><rect width="400" height="400" fill="#526f64"/></svg>':html}));
 await page.goto('https://www.facebook.com/marketplace/');await page.evaluate(c=>window.__marketOnlyCss=c,asset('marketplace.css'));await page.evaluate(asset('marketplace.js'));await page.waitForTimeout(350);
 async function test(name,fn){try{await fn();results.push({name,passed:true});console.log('PASS:',name)}catch(e){results.push({name,passed:false,error:e.message});console.error('FAIL:',name,e.message)}}
 await test('standard cards show their supplied location below the title',async()=>{const loc=page.locator('#card-1 [data-mo-summary-location]');assert.equal(await loc.innerText(),'Gold Coast, QLD');assert(await loc.isVisible());const a=await page.locator('#card-1 [data-mo-summary-title]').boundingBox(),b=await loc.boundingBox();assert(b.y>=a.y+a.height);assert(b.width<=178)});
 await test('reduced-price cards use the current price and keep the location',async()=>{assert.equal(await page.locator('#card-2 [data-mo-summary-title]').innerText(),'$1,000 · 2019 Subaru Outback');assert.equal(await page.locator('#card-2 [data-mo-summary-location]').innerText(),'Murphys Creek, QLD')});
 await test('a location supplied without a state is retained',async()=>assert.equal(await page.locator('#card-4 [data-mo-summary-location]').innerText(),'Brisbane'));
 await test('cards with no location do not borrow one from another listing',async()=>assert.equal(await page.locator('#card-3 [data-mo-summary-location]').count(),0));
 await test('the location line opens the original listing',async()=>{await page.locator('#card-2 [data-mo-summary-location]').click();assert.equal(await page.evaluate(()=>window.opened),2)});
 await test('late location metadata appears without a reload',async()=>{await page.locator('#card-3 .caption').evaluate(e=>e.insertAdjacentHTML('beforeend','<span>Toowoomba, QLD</span>'));await page.waitForTimeout(350);assert.equal(await page.locator('#card-3 [data-mo-summary-location]').innerText(),'Toowoomba, QLD')});
 await test('a recycled card cannot retain the previous location',async()=>{await page.locator('#card-3 .caption').evaluate(e=>e.innerHTML='<span>$800</span><span>New listing</span>');await page.waitForTimeout(350);assert.equal(await page.locator('#card-3 [data-mo-summary-location]').count(),0);assert.equal(await page.locator('#card-3 [data-mo-summary-title]').innerText(),'$800 · New listing')});
 await test('caption refreshes settle without duplicates or horizontal overflow',async()=>{await page.evaluate(()=>{for(let i=0;i<4;i++)window.__marketOnlyLayout()});await page.waitForTimeout(350);assert.equal(await page.locator('[data-mo-summary]').count(),4);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);const mutations=await page.evaluate(()=>new Promise(resolve=>{let n=0;const o=new MutationObserver(r=>n+=r.length);o.observe(document.body,{subtree:true,childList:true,attributes:true});setTimeout(()=>{o.disconnect();resolve(n)},300)}));assert.equal(mutations,0)});
 await page.screenshot({path:path.join(base,'test-output/location-captions.png'),fullPage:true});fs.writeFileSync(path.join(base,'test-output/location-caption-results.json'),JSON.stringify({scope:'Controlled Chromium listing fixtures; no live Facebook or Android device.',results},null,2));await browser.close();if(results.some(r=>!r.passed))process.exitCode=1;
})();
