/* Reproductions of map/description wrappers from the reported phone screenshots. */
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright');
const base=path.resolve(__dirname,'..'),asset=n=>fs.readFileSync(path.join(base,'app/src/main/assets',n),'utf8');
const image='https://scontent.example.fbcdn.net/map.jpg';
const mapSvg='<svg xmlns="http://www.w3.org/2000/svg" width="500" height="90"><rect width="500" height="90" fill="#17434a"/><path d="M0 20L500 70M180 0L250 90M300 0L210 90" fill="none" stroke="#617273" stroke-width="3"/><text x="150" y="50" fill="white" font-size="22">Brisbane</text></svg>';
const description=`<div id="description-body"><span dir="auto" id="words">Vintage four poster bed. Handmade, king size frame only.<span hidden id="expanded"> Collection this weekend. This is the full seller description with all its details.</span></span> <button id="expand" onclick="let e=document.querySelector('#expanded');e.hidden=!e.hidden;this.textContent=e.hidden?'See more':'See less'">See more</button></div>`;
function fixture(type){
 const generic=type==='generic';
 const facts=generic?'<div id="facts"><h2 id="facts-heading">Details</h2><div id="condition"><strong>Condition</strong><span>Used - Good</span></div></div>':'<section id="facts"><h2 id="facts-heading">About this vehicle</h2><p>Driven 62,384 km</p><p>Manual transmission</p></section>';
 let renderer=`<div class="map-pixels" style="background-image:url('${image}')"></div>`;
 if(type==='image')renderer=`<img class="map-pixels" alt="Approximate area" src="${image}">`;
 if(type==='canvas')renderer='<canvas class="map-pixels" aria-label="Location map"></canvas>';
 if(type==='svg')renderer='<svg class="map-pixels" aria-label="Map" viewBox="0 0 328 72"><rect width="328" height="72" fill="#17434a"/><text x="100" y="40" fill="white">Brisbane</text></svg>';
 const map=`<div id="map" onclick="window.mapClicked=true">${renderer}<button id="map-info" aria-label="Map information" onclick="event.stopPropagation();window.infoClicked=true">i</button></div>`;
 const caption=`<div id="caption-slot" ${type==='zero'?'style="height:0;position:relative"':''}><div id="location" ${type==='zero'?'style="position:absolute;top:0;height:0"':''}><span>Brisbane, QLD</span><span> · Location is approximate</span></div></div><hr id="separator">`;
 const seller='<section id="seller"><h2>Seller information</h2><button id="seller-link" onclick="window.sellerClicked=true">Seller details</button><p>Example seller</p></section>';
 const details=(generic?'':facts)+'<div id="combined" style="padding:16px">'+(generic?facts:'<h2 id="description-heading">Seller\'s description</h2>')+description+(type==='missing'?'':map)+'</div>'+caption+seller;
 return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;color:#e4e6eb;background:#242526;font:16px Arial}h1{font-size:25px}h2{font-size:18px;margin:0 0 16px}section,#title{padding:16px}p{margin:8px 0}#actions{display:flex;gap:8px}#actions button{flex:1}button{border:0;border-radius:6px;background:#3a3b3c;color:#e4e6eb;padding:10px}#expand{padding:0;background:none;font-weight:bold;font-size:16px}#description-body{line-height:1.5;margin-bottom:16px}#facts-heading{padding:16px}#condition{display:flex;gap:24px}#map{height:72px;position:relative;border-radius:8px;overflow:hidden}.map-pixels{display:block;width:100%;height:72px;background-size:cover;object-fit:cover}#map-info{position:absolute;right:8px;top:20px;border-radius:50%;background:white;color:black;padding:4px 9px}#location{font-size:13px;line-height:18px}hr{margin:0 16px;border:0;border-top:1px solid #626363}#seller-link{float:right}#message{border-top:1px solid #444}#message form{display:flex;gap:8px;margin-top:12px}input{width:100%;min-width:0;background:#242526;color:white;border:1px solid #444;border-radius:8px;padding:12px}main{padding-bottom:160px}</style></head><body><main><div id="sections"><div id="title"><h1>Example listing</h1><p>A$600</p><p id="listed">Listed in Brisbane, QLD</p></div><section id="message"><span>Send seller a message</span><form onsubmit="event.preventDefault();window.sent=true"><input id="draft" aria-label="Message seller" value="Hey mate,"><button>Send</button></form></section><section id="actions"><button onclick="window.saved=true">Save</button><button onclick="window.shared=true">Share</button><button aria-label="More options" onclick="window.more=true">…</button></section>${details}</div></main></body></html>`;
}
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.TEST_CHROME||chromium.executablePath(),args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:360,height:628},isMobile:true,hasTouch:true});page.setDefaultTimeout(1800);let type='background';const results=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',r=>r.fulfill({status:200,contentType:r.request().resourceType()==='image'?'image/svg+xml':'text/html; charset=utf-8',body:r.request().resourceType()==='image'?mapSvg:fixture(type)}));
 async function open(t='background'){type=t;await page.goto('https://www.facebook.com/marketplace/item/1/');await page.evaluate(()=>window.originals=[...document.querySelectorAll('#map,#map-info,#location,#words,#expand,#draft')].map(e=>({e,parent:e.parentNode})));await page.evaluate(asset('adblock.js'));await page.evaluate(asset('media.js'));await page.evaluate(c=>window.__marketOnlyCss=c,asset('marketplace.css'));await page.evaluate(asset('marketplace.js'));await page.evaluate(asset('detail.js'));await page.waitForTimeout(400)}
 const box=id=>page.locator(id).evaluate(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,right:r.right,bottom:r.bottom,width:r.width,height:r.height}});
 async function check(withMap=true){
  let prev=-Infinity;for(const id of ['#listed','#actions','#description-body','#facts-heading','#message',...(withMap?['#map']:[]),'#location','#seller']){let b=await box(id);assert(b.y>=prev-1,id+' out of order');prev=b.bottom}
  const description=await page.locator('#words').evaluate(e=>{const r=document.createRange();r.selectNodeContents(e);return r.getClientRects()[0].left});assert(description>=15.5,'description touches screen edge');
  const caption=await box('#location');assert(caption.x>=15.5&&caption.right<=344.5,'caption margins');assert(caption.height>=18,'caption has no flow height');
  if(withMap){let map=await box('#map');assert(map.x>=15.5&&map.right<=344.5,'map margins');assert(caption.y>=map.bottom&&caption.y-map.bottom<=24,'map separated from caption')}
  if(await page.locator('#condition').count()){const h=await box('#facts-heading'),c=await box('#condition'),m=await box('#message');assert(c.y>=h.bottom&&c.bottom<=m.y,'condition detached from Details');}
  const line=await box('#separator');assert(line.y>=caption.bottom,'divider crosses location text');assert((await box('#seller')).y>=line.bottom,'seller overlaps divider');
 }
 async function test(name,fn){try{await fn();results.push({name,passed:true});console.log('PASS:',name)}catch(e){results.push({name,passed:false,error:e.message});console.error('FAIL:',name,e.message)}}
 for(const t of ['background','generic','image','canvas','svg','zero'])await test(t+' map stays with its caption after messaging and has even insets',async()=>{await open(t);await check()});
 await test('expanding and collapsing seller text preserves map order and spacing',async()=>{await open();for(let i=0;i<3;i++){await page.locator('#expand').click();await page.waitForTimeout(300);await check()}});
 await test('existing map, info, Save, Share, menu and message draft stay intact',async()=>{await open();await page.locator('#draft').fill('Please keep this draft');await page.locator('#map-info').click();await page.locator('#map').click({position:{x:20,y:20}});await page.locator('#actions button').nth(0).click();await page.locator('#actions button').nth(1).click();await page.locator('#actions button').nth(2).click();assert(await page.evaluate(()=>infoClicked&&mapClicked&&saved&&shared&&more&&originals.every(x=>x.e.isConnected&&x.e.parentNode===x.parent)));assert.equal(await page.locator('#draft').inputValue(),'Please keep this draft');assert.equal(await page.evaluate(()=>!!window.sent),false)});
 await test('a missing map keeps its real location caption without inventing a map',async()=>{await open('missing');await check(false);assert.equal(await page.locator('[data-mo-detail-map]').count(),0)});
 await test('map photos keep their native map action instead of the gallery viewer',async()=>{await open('image');assert.equal(await page.locator('#map [data-mo-enlarge]').count(),0);await page.locator('#map img').click({position:{x:20,y:20}});assert(await page.evaluate(()=>window.mapClicked))});
 await test('replacing the map and location updates cleanly without duplicate blocks',async()=>{await open();await page.locator('#map').evaluate(e=>e.outerHTML=e.outerHTML);await page.locator('#location').evaluate(e=>e.innerHTML='<span>Gold Coast, QLD</span><span> · Location is approximate</span>');await page.waitForTimeout(400);await check();assert.equal(await page.locator('#map').count(),1);assert((await page.locator('#location').innerText()).includes('Gold Coast'))});
 await test('320px screens wrap long location captions above the divider',async()=>{await open('zero');await page.setViewportSize({width:320,height:628});await page.locator('#location').evaluate(e=>e.innerHTML='<span>Long town name in Northern Queensland, QLD</span><span> · Location is approximate</span>');await page.waitForTimeout(400);const a=await box('#location'),b=await box('#separator');assert(a.height>=36);assert(b.y>=a.bottom);assert(a.right<=304.5);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.setViewportSize({width:360,height:628})});
 await test('repeated passes settle and leaving a listing restores original nodes',async()=>{await open();await page.evaluate(()=>{for(let i=0;i<4;i++)window.__marketOnlyDetailLayout()});await page.waitForTimeout(400);await check();const n=await page.evaluate(()=>new Promise(resolve=>{let n=0;const o=new MutationObserver(r=>n+=r.length);o.observe(document.body,{subtree:true,childList:true,attributes:true});setTimeout(()=>{o.disconnect();resolve(n)},350)}));assert.equal(n,0);await page.evaluate(()=>{history.pushState({},'', '/login/');window.__marketOnlyDetailLayout()});assert.equal(await page.locator('[data-mo-detail-map],[data-mo-detail-inset],[data-mo-detail-location-flow]').count(),0);assert(await page.evaluate(()=>originals.every(x=>x.e.isConnected&&x.e.parentNode===x.parent)));assert.deepEqual(errors,[])});
 await open('generic');await page.screenshot({path:path.join(base,'test-output/map-detail-fixture.png'),fullPage:true});fs.writeFileSync(path.join(base,'test-output/map-detail-results.json'),JSON.stringify({scope:'Controlled Chromium structural regressions for screenshot map layouts; no Android or authenticated Facebook test.',results},null,2));await browser.close();if(results.some(r=>!r.passed))process.exitCode=1;
})();
