/* Mixed Marketplace DOM fixtures. No signed-in Facebook or native Android test. */
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require('playwright');
const base=path.resolve(__dirname,'..');
const css=fs.readFileSync(path.join(base,'app/src/main/assets/marketplace.css'),'utf8');
const js=fs.readFileSync(path.join(base,'app/src/main/assets/marketplace.js'),'utf8');
const picture=(color,label)=>'data:image/svg+xml,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="400" height="400"><rect width="400" height="400" fill="${color}"/><text x="200" y="210" text-anchor="middle" font-size="35" fill="white">${label}</text></svg>`);
function card(id,split=false){const metadata=`<div class="caption"><span>$${id}00</span><span>Listing ${id}</span><span>Gold Coast, QLD</span></div>`;
 return `<div class="cell" id="cell-${id}" style="width:600px;min-height:440px"><div class="chain" style="width:580px"><a href="/marketplace/item/${id}/" onclick="event.preventDefault();window.opened='${id}'"><div style="position:relative;padding-top:100%"><div><img src="${picture('#657965','Listing '+id)}" style="position:absolute;inset:0;width:100%;height:100%"></div></div>${split?'':metadata}</a>${split?`<a href="/marketplace/item/${id}/" onclick="event.preventDefault();window.opened='${id}'">${metadata}</a>`:''}</div></div>`;}
function fixture(){return `<!doctype html><html><head><meta name="viewport" content="width=device-width, initial-scale=1"><style>
 body{margin:0;font:16px Arial}a{color:inherit;text-decoration:none}.caption span{display:block}.row{display:flex;flex-wrap:wrap}button{padding:12px;color:white;background:#3a3b3c;border:0}
 #desktop-toolbar{padding-top:56px;min-height:130px}#location-shell{min-height:60px;padding:16px}#ad{padding:12px}#ad-media{position:relative;padding-top:100%;height:0}#ad-media img{position:absolute;inset:0;width:100%;height:100%}
 </style></head><body><div id="desktop-toolbar"><h1>Marketplace</h1><div style="height:100px"><a href="/marketplace/you/" aria-label="Your Marketplace profile">Profile</a><a href="/marketplace/create/item/">Sell</a><input placeholder="Search Marketplace"></div><hr></div>
 <main role="main"><div id="location-shell"><button aria-label="Change location" onclick="window.locationClicked=true">Gold Coast · 250 km</button></div>
 <div id="collection"><div class="row">${card(1)}${card(2)}</div>
 <div id="ad"><a href="https://example.test/ad" onclick="event.preventDefault();window.adClicked=true"><div id="ad-media"><img src="${picture('#75654a','Advertisement')}"></div><strong>Example advertiser</strong><div>Advertisement title</div><span>Ad</span></a></div>
 <div id="solo-region">${card(3)}</div><div class="row">${card(4)}${card(5,true)}</div></div></main></body></html>`;}
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.TEST_CHROME||chromium.executablePath(),args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:384,height:760}});page.setDefaultTimeout(1500);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',r=>r.fulfill({status:200,contentType:'text/html; charset=utf-8',body:fixture()}));
 await page.goto('https://www.facebook.com/marketplace/');await page.evaluate(c=>{window.__marketOnlyCss=c;window.__marketOnlyHideAds=false},css);await page.evaluate(fs.readFileSync(path.join(base,'app/src/main/assets/adblock.js'),'utf8'));await page.evaluate(js);await page.waitForTimeout(350);
 const results=[];async function test(name,fn){try{await fn();results.push({name,passed:true});console.log('PASS:',name);}catch(e){results.push({name,passed:false,error:e.message});console.error('FAIL:',name,e.message);}}
 await test('duplicate desktop toolbar and its reserved height are removed',async()=>{assert.equal(await page.locator('#desktop-toolbar').isVisible(),false);assert((await page.locator('[data-mo-photo]').first().boundingBox()).y<=48);});
 await test('location summary occupies one compact row and stays functional',async()=>{assert((await page.locator('#location-shell').boundingBox()).height<=44);assert(await page.evaluate(()=>window.__marketOnlyAction('location')));assert(await page.evaluate(()=>window.locationClicked));});
 await page.screenshot({path:path.join(base,'test-output/mixed-layout-initial.png'),fullPage:true});
 await test('isolated listing after an ad has the same square photo size as a pair',async()=>{const photo=await page.locator('#cell-3 [data-mo-photo]').boundingBox();assert(photo);assert(Math.abs(photo.width-190)<1);assert(Math.abs(photo.height-190)<1);assert((await page.locator('#cell-3').boundingBox()).height<270);});
 await test('ad is compact, fully visible and remains labelled',async()=>{const r=await page.locator('#ad').boundingBox();assert(r.width<=192&&r.height<=320,JSON.stringify(r));assert(await page.locator('#ad span').isVisible());assert.equal(await page.locator('#ad img').evaluate(e=>getComputedStyle(e).objectFit),'contain');});
 await test('original ad click is preserved',async()=>{await page.locator('#ad strong').click();assert(await page.evaluate(()=>window.adClicked));});
 await test('separate photo and text links get one accurate caption',async()=>{assert.equal(await page.locator('#cell-5 [data-mo-summary-title]').textContent(),'$500 · Listing 5');assert.equal(await page.locator('#cell-5 .caption').isVisible(),false);await page.locator('#cell-5 [data-mo-summary]').click();assert.equal(await page.evaluate(()=>window.opened),'5');});
 await test('hidden website controls can still be restored',async()=>{await page.evaluate(()=>window.__marketOnlyAction('controls'));assert(await page.locator('#desktop-toolbar').isVisible());await page.evaluate(()=>window.__marketOnlyAction('controls'));});
 await test('adding another listing to an isolated group forms a normal pair',async()=>{await page.locator('#solo-region').evaluate((e,html)=>e.insertAdjacentHTML('beforeend',html),card(6));await page.waitForTimeout(350);const a=await page.locator('#cell-3').boundingBox(),b=await page.locator('#cell-6').boundingBox();assert.equal(a.y,b.y);assert(Math.abs(a.width-190)<1&&Math.abs(b.width-190)<1);});
 await test('narrow screens preserve compact ads and listing widths',async()=>{await page.setViewportSize({width:320,height:740});await page.waitForTimeout(250);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(Math.abs((await page.locator('#cell-3 [data-mo-photo]').boundingBox()).width-158)<1);assert((await page.locator('#ad').boundingBox()).width<=160);await page.setViewportSize({width:384,height:760});});
 await test('missing location control leaves filters revealed',async()=>{await page.locator('#location-shell').evaluate(e=>e.remove());assert.equal(await page.evaluate(()=>window.__marketOnlyAction('location')),false);assert(await page.locator('#desktop-toolbar').isVisible());await page.evaluate(()=>window.__marketOnlyAction('controls'));});
 await test('layout settles without repeating DOM mutations',async()=>{await page.waitForTimeout(400);const mutations=await page.evaluate(()=>new Promise(resolve=>{let count=0;const observer=new MutationObserver(records=>count+=records.length);observer.observe(document.body,{childList:true,attributes:true,subtree:true});setTimeout(()=>{observer.disconnect();resolve(count)},500)}));assert.equal(mutations,0);assert.deepEqual(errors,[]);});
  await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(base,'test-output/mixed-layout-fixture.png'),fullPage:true});
 await test('a recycled advertisement wrapper loses its obsolete ad sizing',async()=>{await page.locator('#ad').evaluate((e,html)=>e.innerHTML=html,card(7));await page.waitForTimeout(350);assert.equal(await page.locator('#ad').getAttribute('data-mo-ad'),null);assert(Math.abs((await page.locator('#cell-7 [data-mo-photo]').boundingBox()).width-190)<1);});
 await test('a single direct listing never applies sizing to body or html',async()=>{await page.locator('main').evaluate((e,html)=>{e.innerHTML=html;const cell=e.querySelector('.cell');e.replaceChildren(cell.querySelector('a'));},card(8));await page.waitForTimeout(350);assert.equal(await page.locator('body').getAttribute('data-mo-chain'),null);assert.equal(await page.locator('html').getAttribute('data-mo-chain'),null);const photo=await page.locator('main [data-mo-photo]').boundingBox();assert(Math.abs(photo.width-190)<1);});
 await test('recycled cards cannot retain an outdated generated price',async()=>{await page.locator('main .caption').evaluate(e=>e.innerHTML='<span>Listing unavailable</span>');await page.waitForTimeout(350);assert.equal(await page.locator('main [data-mo-summary]').count(),0);assert(await page.locator('main .caption').isVisible());assert.deepEqual(errors,[]);});
 fs.writeFileSync(path.join(base,'test-output/mixed-layout-results.json'),JSON.stringify({scope:'Controlled DOM fixtures only, not native Android or live Facebook.',results},null,2));
 await browser.close();if(results.some(x=>!x.passed))process.exitCode=1;
})();
