/* Regression shapes based on screenshots: grouped ad/listing and padded headers.
   Controlled browser DOM, not a captured Facebook page or Android runtime. */
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require('playwright');
const base=path.resolve(__dirname,'..');
const css=fs.readFileSync(path.join(base,'app/src/main/assets/marketplace.css'),'utf8');
const js=fs.readFileSync(path.join(base,'app/src/main/assets/marketplace.js'),'utf8');
const img=(color,label)=>'data:image/svg+xml,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="300" height="300"><rect width="300" height="300" fill="${color}"/><text x="150" y="155" text-anchor="middle" font-size="24" fill="white">${label}</text></svg>`);
function card(id){return `<div id="card-${id}" class="cell"><a href="/marketplace/item/${id}/" onclick="event.preventDefault();window.clicked='${id}'"><div class="photo"><img src="${img('#526e60','Listing '+id)}"></div><div class="caption"><span>$${id}00</span><span>Listing ${id}</span></div></a></div>`;}
function ad(id=1){return `<div id="ad-${id}" class="ad"><a href="https://example.test/ad" onclick="event.preventDefault();window.adClicked=true"><div class="photo"><img src="${img('#756343','Advertisement')}"></div><div><span>Example advertiser</span><span class="disclosure">Ad</span></div></a></div>`;}
function fixture(){return `<!doctype html><html><head><meta name="viewport" content="width=device-width, initial-scale=1"><style>
html{height:100%;overflow-x:hidden}body{height:100%;margin:0;padding-top:60px;background:#242526;color:white;font:16px Arial}
#header-spacer{height:56px}#page-shell{padding-top:24px}#location-panel{min-height:108px;padding:24px 0;box-sizing:border-box}#location-inner{padding:16px 0}
.location-label{font-size:18px;line-height:24px;color:#65aeff;cursor:pointer}.row{display:flex}.cell{width:600px;padding:10px}.photo{position:relative;padding-top:100%}.photo img{position:absolute;inset:0;width:100%;height:100%}.caption span{display:block}a{color:inherit;text-decoration:none}
</style></head><body><div role="banner">Facebook</div><div id="header-spacer"></div><div id="page-shell"><main role="main">
<div id="location-panel"><h2>Today's picks</h2><div id="location-inner"><span role="link" tabindex="0" class="location-label" onclick="window.locationClicked=true">Gold Coast · 250 km</span></div></div>
<div id="results"><div class="row">${card(1)}${card(2)}</div><div id="ad-listing-batch"><div id="ad-slot">${ad()}</div><div id="listing-slot">${card(3)}</div></div><div class="row">${card(4)}${card(5)}</div></div></main></div></body></html>`;}
(async()=>{
const browser=await chromium.launch({executablePath:process.env.TEST_CHROME||chromium.executablePath(),args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:384,height:760}});page.setDefaultTimeout(1500);const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',r=>r.fulfill({status:200,contentType:'text/html; charset=utf-8',body:fixture()}));
await page.goto('https://www.facebook.com/marketplace/');await page.evaluate(c=>{window.__marketOnlyCss=c;window.__marketOnlyHideAds=false},css);await page.evaluate(fs.readFileSync(path.join(base,'app/src/main/assets/adblock.js'),'utf8'));await page.evaluate(js);await page.waitForTimeout(400);
const results=[];async function test(name,fn){try{await fn();results.push({name,passed:true});console.log('PASS:',name)}catch(e){results.push({name,passed:false,error:e.message});console.error('FAIL:',name,e.message)}}
await test('header spacer and nested location padding collapse to one row',async()=>{const first=await page.locator('#card-1 [data-mo-photo]').boundingBox();assert(first.y<=44,JSON.stringify(first));assert((await page.locator('#location-panel').boundingBox()).height<=44);});
await test('non-button location link remains clickable from the native pin action',async()=>{assert(await page.evaluate(()=>window.__marketOnlyAction('location')));assert(await page.evaluate(()=>window.locationClicked));});
await test('ad and listing sharing a batch occupy opposite columns',async()=>{const a=await page.locator('#ad-slot').boundingBox(),b=await page.locator('#listing-slot').boundingBox();assert(Math.abs(a.y-b.y)<1,JSON.stringify({a,b}));assert(Math.abs(a.width-190)<1&&Math.abs(b.width-190)<1);assert(b.x>=194);});
await test('listing caption never hides the neighbouring advertisement disclosure',async()=>{assert(await page.locator('.disclosure').isVisible());assert.equal(await page.locator('#card-3 [data-mo-summary]').textContent(),'$300 · Listing 3');assert.equal(await page.locator('#ad-1 [data-mo-original-caption]').count(),0);});
await test('ad and listing preserve their original click handlers',async()=>{await page.locator('.disclosure').click();assert(await page.evaluate(()=>window.adClicked));await page.locator('#card-3 [data-mo-summary]').click();assert.equal(await page.evaluate(()=>window.clicked),'3');});
await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(base,'test-output/nested-layout-initial.png'),fullPage:true});
await test('a nested batch retains two columns at 320 CSS pixels',async()=>{await page.setViewportSize({width:320,height:740});const a=await page.locator('#ad-slot').boundingBox(),b=await page.locator('#listing-slot').boundingBox();assert(Math.abs(a.width-158)<1&&Math.abs(b.width-158)<1);assert.equal(a.y,b.y);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.setViewportSize({width:384,height:760});});
await test('late-loaded sibling listing stays alongside the ad',async()=>{await page.locator('#listing-slot').evaluate(e=>e.remove());await page.waitForTimeout(300);await page.locator('#ad-listing-batch').evaluate((e,html)=>e.insertAdjacentHTML('beforeend','<div id="listing-slot">'+html+'</div>'),card(6));await page.waitForTimeout(400);const a=await page.locator('#ad-slot').boundingBox(),b=await page.locator('#listing-slot').boundingBox();assert.equal(a.y,b.y);assert(Math.abs(b.width-190)<1);assert(await page.locator('.disclosure').isVisible());});
await test('extra grouping layer never squeezes a two-tile row into one cell',async()=>{await page.locator('#ad-listing-batch').evaluate(e=>{const wrapper=document.createElement('div');e.parentElement.insertBefore(wrapper,e);wrapper.appendChild(e)});await page.waitForTimeout(400);assert(Math.abs((await page.locator('#ad-listing-batch').boundingBox()).width-384)<1);assert(Math.abs((await page.locator('#card-6 [data-mo-photo]').boundingBox()).width-190)<1);});
await test('visible announcement above location is preserved',async()=>{await page.locator('#location-panel').evaluate(e=>e.insertAdjacentHTML('afterbegin','<div role="status" id="notice">Location could not be updated</div>'));await page.waitForTimeout(350);assert(await page.locator('#notice').isVisible());});
await test('controls mode restores the original header spacing',async()=>{await page.evaluate(()=>window.__marketOnlyAction('controls'));assert(await page.locator('#location-panel h2').isVisible());assert((await page.locator('#header-spacer').boundingBox()).height>=56);await page.evaluate(()=>window.__marketOnlyAction('controls'));});
await test('layout settles after dynamic updates',async()=>{await page.waitForTimeout(400);const n=await page.evaluate(()=>new Promise(resolve=>{let count=0;const o=new MutationObserver(r=>count+=r.length);o.observe(document.body,{childList:true,attributes:true,subtree:true});setTimeout(()=>{o.disconnect();resolve(count)},500)}));assert.equal(n,0);assert.deepEqual(errors,[]);});
fs.writeFileSync(path.join(base,'test-output/nested-layout-results.json'),JSON.stringify({scope:'Controlled DOM fixtures, not a live Facebook or Android device test.',results},null,2));
await browser.close();if(results.some(r=>!r.passed))process.exitCode=1;
})();
