plugins { id 'com.android.application' }
android {
    namespace 'au.sutto.marketonly'
    compileSdk 35
    defaultConfig {
        applicationId 'au.sutto.marketonly'
        minSdk 26
        targetSdk 35
        versionCode 21
        versionName '1.1.18'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_1_8; targetCompatibility JavaVersion.VERSION_1_8 }
    buildTypes {
        debug {
            applicationIdSuffix '.tuned'
            versionNameSuffix '-test'
            resValue 'string', 'app_name', 'MarketOnly Tuned'
        }
    }
}
